Exerciseset2 learning assigning Persistent Volumes with PVC
dergeberl/kubeteach-charts pull request #28
Opened 2023-09-06 13:49 UTC by Duciwuci

2023-09-22 04:57 UTC, dergeberl requested changes

2023-09-22 04:57 UTC, dergeberl commented on charts/exerciseset2/templates/exerciseSet.yaml
> +          description: "Create a Persistent Volume Claim (PVC) in the cluster with the name myfirstpvc in the task01's namespace, request 1Gi storage with RWO access mode"
I would also check the RWO mode in the `resourceCondition` as it is mentioned in the description.

2023-09-22 04:57 UTC, dergeberl commented on charts/exerciseset2/templates/exerciseSet.yaml
> +          description: "Create a Persistent Volume (PV) in the cluster with the name myfirstpv in the task01's namespace, spec 1Gi of capacity with RWO access mode. Moreover, use the hostpath.path /o
```suggestion
          description: "Create a Persistent Volume (PV) in the cluster with the name myfirstpv, spec 1Gi of capacity andRWO access mode. Moreover, use the hostpath.path /opt/volume/nginx and specify the claimRef for task02's PVC"
```
It is not possible to create a PV in a Namespace.

2023-09-22 04:57 UTC, dergeberl commented on charts/exerciseset2/templates/exerciseSet.yaml
> +          description: "Create a Pod pod1 with the nginx:latest image, assign the pod the volume and specify the PVC"
I think we should add also a volumeMount to the task, otherwise the volume cant be used.

2023-12-18 14:36 UTC, Duciwuci commented on solutions/exerciseset2/task04.yaml
> +      - mountPath: "/usr/share/nginx/html"
adjust path to PV

2026-01-03 20:57 UTC, dergeberl commented
I will archive this repo. Thanks for your contribution.

2026-01-03 20:57 UTC, closed without merging